### PR TITLE
Enumeral

### PR DESCRIPTION
**Pull request by jadx2**
Implementation of enumerable methods according to The Odin Project repository.

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
### Hey there :wave: 
#### Well done for making an attempt at recreating the ruby enumerable methods in this project. However, there are still a lot of changes to be made as your methods are failing a lot of test cases(56 out of 74 are failing). Because the failed cases are so many I won't be able to go through them individually but I will try to give a high-level overview of how to go about implementing your methods in order to get them to pass those test cases.
-  [ ] First of all, you need to update your readme to include specifically how to run the project. The instructions you left there is not descriptive enough.
- [ ] The main aim of this project is for you to recreate ruby's enumerable methods. That means the custom methods you write should behave exactly as the original enumerable method behaves. Your methods are failing their test cases because they do not behave exactly as the original ruby enumerable methods behave. I would suggest you take some time to visit the ruby documentation and really study the way the enumerable methods work, this will help you know exactly what is expected of your custom methods and also how to go about implementing them to behave like the original. And to help you confirm that your implementation of the methods is correct, you can use the original methods to test your own custom methods. What I mean is say you finish writing your own implementation of each method i.e your my_each method, to confirm that you did the correct thing you can test it out like so `[1, 2, 3, 4, 5].my_each { |num| p num * 2 } == [1, 2, 3, 4, 5].each { |num| p num * 2 }`. Of course, you will need to test it against several inputs and cases which you can get from the ruby documentation. The most important thing to note is that the methods you write have to behave exactly like the original enumerable methods.
- [ ] Please take your time to understand the enumerable methods and write your own implementation following the suggestion I left above.
- [ ] Do request another review once you are ready.
slack(@ebeagusamuel)

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED :red_circle: :recycle: 
#### Hey team :wave: :wave: , good job on working on implementing your own methods, most of them pass the tests except the following :arrow_down: , kindly work on them


  1) enumerables #my_all? when no block or argument is given returns true when none of the collection members are false or nil
     Failure/Error: expect(true_array.my_all?).to be true_array.all?
     
       expected true
            got false


  2) enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
     Failure/Error: expect(array.my_all?(Integer)).to be array.all?(Integer)
     
       expected true
            got false
     

  3) enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
     Failure/Error: expect(numbers.my_all?(Numeric)).to be numbers.all?(Numeric)
     
       expected true
            got false
  

  4) enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
     Failure/Error: expect(array.my_any?(Numeric)).to be array.any?(Numeric)
     
       expected true
            got false


  5) enumerables #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject  -> multiply_els is not a ruby enumerable so move the method and declare it outside module enumerable.

That's all :smile: , kindly submit another review when done
Feel free to slack me if you have any questions

Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED :red_circle: :recycle: 

#### Hey tean :wave: :wave:  its me again :smile: , good job on working on changes requested above. Keep it up :clap: 

However, before marking the project as complete, lets fix one more method.

- [ ] #my_all. If the argument passed is nil, it should return a false `elsif arg.nil? `

That's all :smile: , kindly submit another review when done
Feel free to slack me if you have any questions

Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
## STATUS :APPROVED :partying_face:  :fireworks: 

#### Hey guys :smile: :wave:  , am back again :laughing: . Anyway, good job on working on all the feedback given, this project is therefore approved. Go ahead and merge. All the best in the next projects :100:  

Happy Coding :computer:  :computer_mouse: 

Regards
Peris Ndanu

**Pull request merged**
